Implement async http requests
Saloodo/mail-bundle pull request #8
Opened 2021-06-28 13:51 UTC by UnnikrishnanBhargavakurup

2021-06-29 14:15 UTC, rnogueira commented on src/Adapters/SalesForceAdapter.php
> +            'timeout' => 60, // in seconds
Does it take 60 seconds to send an e-mail? I think this value can be lower. Same in line 112. Even better if this value is in a constant.

2021-06-29 14:17 UTC, rnogueira approved these changes
Approved with a comment about an improvement.

2021-06-29 14:33 UTC, UnnikrishnanBhargavakurup commented on src/Adapters/SalesForceAdapter.php
> +            'timeout' => 60, // in seconds
@rnogueira - it can take as much time it can because now it's a nonblocking request. So thought of giving more time.

Yes, we need to more it a constant.

2021-06-30 07:58 UTC, shadman requested changes

2021-06-30 09:46 UTC, UnnikrishnanBhargavakurup commented on src/Adapters/SalesForceAdapter.php
> +            return $this->sendEmail($accessToken, $email);
yes, if we get an access token from cache we send email here

2021-06-30 09:47 UTC, UnnikrishnanBhargavakurup commented on src/Adapters/SalesForceAdapter.php
> +                    return $this->sendEmail($accessToken, $email);
after fetching access token we will send email

2021-06-30 10:44 UTC, RamyHakam requested changes

2021-06-30 10:48 UTC, UnnikrishnanBhargavakurup commented on src/EmailSender.php
> +        if (!$promise instanceof RejectedPromise) {
it can be either PENDING or FULFILLED

2021-06-30 14:40 UTC, RamyHakam approved these changes

2021-07-01 10:06 UTC, shadman approved these changes

2021-07-01 10:08 UTC, merged